WTSite/Models/room.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WTSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public room()
        {
            this.children = new HashSet<child>();
            this.waitlists = new HashSet<waitlist>();
        }
    
        public int room_id { get; set; }
        public string room_name { get; set; }
        public int room_age_range_min { get; set; }
        public int room_age_range_max { get; set; }
        public int room_capacity { get; set; }
        public int childcare_facility_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<child> children { get; set; }
        public virtual childcare_facility childcare_facility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<waitlist> waitlists { get; set; }
    }
}

WTSite/Controllers/RoomsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WTSite.DAL;
using WTSite.Helper_Classes;
using WTSite.Models;

namespace WTSite.Controllers
{
    [Authorize(Roles = "Facility, Admin")]
    public class RoomsController : Controller
    {
        private WTEntities db = new WTEntities();
        private RoomDAL rm = null;

        [HttpGet]
        public ActionResult RoomsIndex(int? id = 0)
        {
            
            if (Session["CurrentFacilityId"] == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            id = (int)Session["CurrentFacilityId"];
            int abcd = id.Value;

            List<room> rooms = db.rooms.Where(item => item.childcare_facility_id == id).ToList();

            ViewBag.FacilityId = abcd;

            return View(rooms);
        }

        [ActionName("CreateRoom")]
        public ActionResult CreateRoom(int id)
        {
            // stops facilities from modifying other facility's data
            if (id != (int)Session["CurrentFacilityId"])
            {
                return RedirectToAction("Error", "Home");
            }

            List<room> rooms = db.rooms.Where(item => item.childcare_facility_id == id).ToList();

            rooms.Add(new room { childcare_facility_id = id });

            ViewBag.FacilityId = id;

            return View(rooms);
        }

        [HttpPost]
        [ActionName("AddRoom")]
        public ActionResult AddRoom(List<room> rooms)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Error", "Home");
            }
            else
            {
                // stops facilities from modifying other facility's data
                if (rooms[rooms.Count - 1].childcare_facility_id != (int)Session["CurrentFacilityId"])
                {
                    return RedirectToAction("Error", "Home");
                }

                // if room age min > room age max, send to error page (server-side safe-guard)
                if (rooms[rooms.Count - 1].room_age_range_min > rooms[rooms.Count - 1].room_age_range_max)
                {
                    return RedirectToAction("Error", "Home");
                }

                rm = new RoomDAL(rooms[rooms.Count - 1].childcare_facility_id);

                rm.createRoom(rooms[rooms.Count - 1].room_name, rooms[rooms.Count - 1].room_age_range_min, rooms[rooms.Count - 1].room_age_range_max, rooms[rooms.Count - 1].room_capacity);

                return RedirectToAction("RoomsIndex");
            }
        }

        public ActionResult DeleteRoom(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            room room = db.rooms.Find(id);

            if (room == null)
            {
                return HttpNotFound();
            }
            // stops facilities from modifying other facility's data
            else if (room.childcare_facility_id != (int)Session["CurrentFacilityId"])
            {
                return RedirectToAction("Error", "Home");
            }

            rm = new RoomDAL(room.childcare_facility_id);
            rm.RoomId = room.room_id;
            rm.deleteRoom();

            return RedirectToAction("RoomsIndex");
        }

        [ActionName("EditRoom")]
        public ActionResult EditRoom(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error", "Home");
            }

            room room = db.rooms.Find(id);

            if (Session["CurrentFacilityId"] == null)
            {
                return RedirectToAction("Error", "Home");
            }

            // stops facilities from modifying other facility's data
            if (room.childcare_facility_id != (int)Session["CurrentFacilityId"])
            {
                return RedirectToAction("Error", "Home");
            }

            rm = new RoomDAL(room.childcare_facility_id);
            rm.RoomId = id;

            List<ChildRoster> rosterChildren = rm.getRosterChildren();

            List<ChildWaitlist> waitlistChildren = rm.getWaitlistedChildren();

            List<prioritization> facilityPrioritizations = rm.getFacilityPrioritizations();

            childcare_facility facility = db.childcare_facility.Find(room.childcare_facility_id);

            SearchDAL EEDCalculator = new SearchDAL();
            DateTime EEDWithoutPrioritization = EEDCalculator.getEED(facility, room.room_id, new AlgorithmChild());

            // to hold each prioritization
            List<PrioritizationEED> prioritizationEEDS = new List<PrioritizationEED>();
            int priorityRank = 0;
            DateTime EED = new DateTime();

            if (facilityPrioritizations.Count > 0)
            {
                foreach (prioritization prioritization in facilityPrioritizations)
                {
                    priorityRank = prioritization.priority_rank;
                    EED = EEDCalculator.getEED(facility, room.room_id, new AlgorithmChild(priorityRank));
                    prioritizationEEDS.Add(new PrioritizationEED(prioritization, EED));
                }
            }
            RoomVM roomInfo = new RoomVM(room, room.waitlists.First().waitlist_override_date, rosterChildren, waitlistChildren, facilityPrioritizations, EEDWithoutPrioritization, prioritizationEEDS);

            List<PrioritizationVM> childrenPrioritizationVMs = new List<PrioritizationVM>();

            List<int> selectedIds = new List<int>();
            for (var i = 0; i < waitlistChildren.Count; i++)
            {
                selectedIds = new List<int>();
                var myFacilityPrioritizations = new SelectListItem[facilityPrioritizations.Count];

                for (var j = 0; j < myFacilityPrioritizations.Length; j++)
                {
                    prioritization thepr = waitlistChildren[i].Prioritizations.FirstOrDefault(item => item.prioritization_id == facilityPrioritizations[j].prioritization_id);

                    if (!(thepr == null))
                        selectedIds.Add(thepr.prioritization_id);
                }
                childrenPrioritizationVMs.Add(new PrioritizationVM()
                {
                    PrioritizationID = selectedIds.ToArray(),
                    Prioritizations = new MultiSelectList(facilityPrioritizations, "prioritization_id", "priority_name", selectedIds),
                    ChildId = waitlistChildren[i].ChildId
                });
            }


            EEDAlgorithm calculateEED = new EEDAlgorithm();

            var templistwait = new List<AlgorithmChild>();


            // if the tempWaitlist is not null, convert children to Child and add to waitlist
            if (waitlistChildren.Count > 0)
            {
                foreach (ChildWaitlist child in waitlistChildren)
                {
                    // if the child has prioritizations, create a child with their highest, minimum, priority rank                         
                    if (child.Prioritizations.Count > 0)
                    {
                        int prioritizationRank = (from item in child.Prioritizations
                                                  select item.priority_rank).Min();

                        templistwait.Add(new AlgorithmChild(child.ChildId, child.DOB, prioritizationRank)); // add child to waitlist, to be passed to EEDAlgorithm
                    }
                    // else create a child without a priority rank
                    else
                    {
                        templistwait.Add(new AlgorithmChild(child.ChildId, child.DOB)); // add child to waitlist, to be passed to EEDAlgorithm
                    }
                }
            }

            getAllEEDs(room, rosterChildren, waitlistChildren, calculateEED);

            roomInfo.ChildrenPrioritizationVMs = childrenPrioritizationVMs;
            return View(roomInfo);
        }

        private static void getAllEEDs(room room, List<ChildRoster> rosterChildren, List<ChildWaitlist> waitlistChildren, EEDAlgorithm calculateEED)
        {
            List<AlgorithmChild> templistrost = new List<AlgorithmChild>();
            for (int i = 0; i < waitlistChildren.Count; i++)
            {
                templistrost = new List<AlgorithmChild>();

                DateTime d = new DateTime();
                AlgorithmChild alg = new AlgorithmChild();
                List<AlgorithmChild> tempalgwait = new List<AlgorithmChild>();
                alg.ChildID = waitlistChildren[i].ChildId;
                alg.DOB = waitlistChildren[i].DOB;
                alg.PrioritizationRank = waitlistChildren[i].HighestPrioritizationRank;

                if (rosterChildren.Count > 0)
                {
                    foreach (ChildRoster child in rosterChildren)
                    {
                        if (child.OverrideDate != null)
                        {
                            templistrost.Add(new AlgorithmChild(child.ChildId, child.DOB, (DateTime)child.OverrideDate));
                        }
                        else
                        {
                            templistrost.Add(new AlgorithmChild(child.ChildId, child.DOB));
                        }
                    }
                }

                for (int j = 0; j < (i + 1) - j; j++)
                {
                    if (i != 0)
                    {
                        if (waitlistChildren[j].Prioritizations.Count > 0)
                        {
                            int prioritizationRank = (from item in waitlistChildren[j].Prioritizations
                                                      select item.priority_rank).Min();

WTSite/Views/Rooms/CreateRoom.cshtml
@using WTSite.Models;
@model List<WTSite.Models.room>

@{
    ViewBag.Title = "Add New Room";
    Layout = "~/Views/Shared/_FacilityLayout.cshtml";
}
<h2>Add Room</h2>
<style>
    .help-block{
        position: absolute;
    }
</style>
@using (Html.BeginForm("AddRoom", "Rooms", FormMethod.Post, new { id = "submitNewRoomForm" }))
{
    @Html.ValidationSummary(true)
    @Html.AntiForgeryToken()
    <table class="table">
        <tr>
            <th><strong>Room Name</strong></th>
            <th><strong>Age Range (Months)</strong></th>
            <th><strong>Roster Capacity</strong></th>
        </tr>

        @for (var i = 0; i < Model.Count - 1; i++)
        {
            <tr>
                <td>
                    @Html.HiddenFor(modelItem => Model[i].childcare_facility_id)
                    @Html.HiddenFor(modelItem => Model[i].room_name)
                    @Html.HiddenFor(modelItem => Model[i].room_age_range_min)
                    @Html.HiddenFor(modelItem => Model[i].room_age_range_max)
                    @Html.HiddenFor(modelItem => Model[i].room_capacity)
                    @Html.HiddenFor(modelItem => Model[i].room_id)
                    @Html.DisplayFor(modelItem => Model[i].room_name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model[i].room_age_range_min) to 
                    @Html.DisplayFor(modelItem => Model[i].room_age_range_max) months
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model[i].room_capacity)
                </td>
            </tr>
        }
        <tr>
            <td>
                <strong>Add New: </strong>
               @Html.EditorFor(modelItem => Model[Model.Count - 1].room_name, new { htmlAttributes = new { maxlength = "60", data_validation = "required alphanumeric", data_validation_allowing = " ", data_validation_error_msg = "Enter a room name. No special characters allowed." } })
            </td>
            <td>
                @Html.EditorFor(modelItem => Model[Model.Count - 1].room_age_range_min, new { htmlAttributes = new { @class = "ageMinTxtBox", maxlength = "2", min = "0", max = "83", style = "max-width:70px", data_validation = "number required", data_validation_allowing = "range[0;83]", data_validation_error_msg = "Please specify a minimum age between 0 and 83 months." } }) to @Html.EditorFor(modelItem => Model[Model.Count - 1].room_age_range_max, new { htmlAttributes = new { @class = "ageMaxTxtBox", maxlength = "2", min = "0", max = "83", style = "max-width:70px", data_validation = "number required", data_validation_allowing="range[0;83]", data_validation_error_msg = "Please specify a maximum age between 0 and 83 months." } }) months
            </td>
            <td>
                @Html.EditorFor(modelItem => Model[Model.Count - 1].room_capacity, new { htmlAttributes = new { maxlength = "2", min = "1", max = "99", style = "max-width:70px", data_validation = "number required", data_validation_allowing = "range[1;99]", data_validation_error_msg = "Please enter a room capacity greater than 0." } })
            </td>
        </tr>
    </table>
    @Html.HiddenFor(modelItem => Model[Model.Count - 1].room_id)
    @Html.HiddenFor(modelItem => Model[Model.Count - 1].childcare_facility_id)
    <input type="submit" value="Add Room" class="btn-sm btn-primary" id="SaveRoomChangesBtn" /> @Html.ActionLink("Cancel", "RoomsIndex", new { id = ViewBag.FacilityId }, new { @class = "btn-sm btn-secondary" })
    <p><div id="errMsg"><span></span></div></p>
}
<script src="~/Content/jqueryui/jquery-ui.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.2.43/jquery.form-validator.min.js"></script>
<script>
    $.validate({
        modules: 'date'
    });
    $("#errMsg").hide();
    $('.ageMinTxtBox').change(function () {
        var minAgeVal = $(this).val();
        var maxAgeVal = $('.ageMaxTxtBox').val();
        var minAge = parseInt(minAgeVal, 10);
        var maxAge = parseInt(maxAgeVal, 10);
        if (minAge > maxAge) {
            $("#errMsg").show();
            $("#errMsg").addClass('ui-state-error ui-corner-all');
            $("#errMsg span").text('Age range is invalid.');
            $("#SaveRoomChangesBtn").prop('disabled', true);
            $("#SaveRoomChangesBtn").removeClass('btn-primary');
            $("#SaveRoomChangesBtn").addClass('btn-default');
        }
        if (minAge <= maxAge) {
            $("#errMsg").hide();
            $("#errMsg").removeClass('ui-state-error ui-corner-all');
            $("#SaveRoomChangesBtn").prop('disabled', false);
            $("#SaveRoomChangesBtn").removeClass('btn-default');
            $("#SaveRoomChangesBtn").addClass('btn-primary');
        }
    });
    $('.ageMaxTxtBox').change(function () {
        var maxAgeVal = $(this).val();
        var minAgeVal = $('.ageMinTxtBox').val();
        var minAge = parseInt(minAgeVal, 10);
        var maxAge = parseInt(maxAgeVal, 10);
        if (minAge > maxAge) {
            $("#errMsg").show();
            $("#errMsg").addClass('ui-state-error ui-corner-all');
            $("#errMsg span").text('Age range is invalid.');
            $("#SaveRoomChangesBtn").prop('disabled', true);
            $("#SaveRoomChangesBtn").removeClass('btn-primary');
            $("#SaveRoomChangesBtn").addClass('btn-default');
        }
        if (minAge <= maxAge) {
            $("#errMsg").hide();
            $("#errMsg").removeClass('ui-state-error ui-corner-all');
            $("#SaveRoomChangesBtn").prop('disabled', false);
            $("#SaveRoomChangesBtn").removeClass('btn-default');
            $("#SaveRoomChangesBtn").addClass('btn-primary');
        }
    });
</script>

WTSite/Views/Rooms/CreateRosterChild.cshtml
@model WTSite.Models.RoomVM

@{
    ViewBag.Title = "Add New Child to Roster";
    Layout = "~/Views/Shared/_FacilityLayout.cshtml";
}

<br />
<h4>Add New Child to Roster</h4>
<h5><strong>Room:</strong> @Html.DisplayFor(modelItem => Model.Room.room_name)</h5>

@*<table class="table">
    <tr>
        <td>
            @Html.HiddenFor(modelItem => Model.Room.childcare_facility_id)
            @Html.HiddenFor(modelItem => Model.Room.room_id)
            Room Name: @Html.DisplayFor(modelItem => Model.Room.room_name)
        </td>
        <td>
            Room Age Range (Months): @Html.DisplayFor(modelItem => Model.Room.room_age_range_min) to @Html.DisplayFor(modelItem => Model.Room.room_age_range_max)
        </td>
        <td>
            Room Capacity: @Html.DisplayFor(modelItem => Model.Room.room_capacity)
        </td>
        <td>
            Waitlist Override Date (Optional): @Html.DisplayFor(modelItem => Model.WaitlistOverrideDate)
        </td>
    </tr>
</table>

<hr />*@

@using (Html.BeginForm("AddRosterChild", "Rooms", FormMethod.Post, new { id = "submitNewRosterChildForm" }))
{
    <table class="table">
        <tr>
            <th><strong>Child Name/Identifier</strong> <font id="tooltip" style="font-size: 9px; font-weight:bold;"><a href="#" title="For security reasons, please use first names only or another unique identifier."><i class="fa fa-2x fa-question-circle"></i></a></font></th>
            <th><strong>Date of Birth</strong></th>
            <th><strong>Override Leave Date (Optional)</strong></th>
            <th><strong></strong></th>
        </tr>
        @for (var i = 0; i < Model.RosterChildren.Count - 1; i++)
        {
            <tr>
                <td>
                    @Html.HiddenFor(modelItem => Model.RosterChildren[i].ChildId)
                    @Html.HiddenFor(modelItem => Model.RosterChildren[i].ChildName)
                    @Html.HiddenFor(modelItem => Model.RosterChildren[i].DOB) 
                    @Html.DisplayFor(modelItem => Model.RosterChildren[i].ChildName)
                </td>
                <td>
                    @Convert.ToString(string.Format("{0:MM/dd/yyyy}", Model.RosterChildren[i].DOB))
                </td>
                <td>
                    @Convert.ToString(string.Format("{0:MM/dd/yyyy}", Model.RosterChildren[i].OverrideDate))
                </td>
                <td></td>
            </tr>
        }
        <tr>
            <td>
                @Html.HiddenFor(modelItem => Model.Room.childcare_facility_id)
                @Html.HiddenFor(modelItem => Model.Room.room_name)
                @Html.HiddenFor(modelItem => Model.Room.room_age_range_min)
                @Html.HiddenFor(modelItem => Model.Room.room_age_range_max)
                @Html.HiddenFor(modelItem => Model.Room.room_capacity)
                @Html.HiddenFor(modelItem => Model.Room.room_id)
                @Html.TextBoxFor(modelItem => Model.RosterChildren[Model.RosterChildren.Count - 1].ChildName, new { @data_validation = "required alphanumeric", @class = "form-control input", @maxlength = "15", style = "max-width:200px;", @data_validation_error_msg = "Child identifier is required and cannot contain spaces." })
            </td>
            <td>
                @Html.TextBoxFor(modelItem => Model.RosterChildren[Model.RosterChildren.Count - 1].DOB, "{0:MM/dd/yyyy}", new { @style = "max-width:120px;", @class = "CreateRostChildDatePicker form-control input", @data_validation = "required", @value = "", @id = "crcdob", @data_validation_error_msg = "Date of birth is required." })
            </td>
            <td>
                @Html.TextBoxFor(modelItem => Model.RosterChildren[Model.RosterChildren.Count - 1].OverrideDate, "{0:MM/dd/yyyy}", new { @style = "max-width:120px;", @class = "CreateRostChildDatePicker form-control input", @value = "", @id = "crcOverrideDate" })
            </td>
            <td></td>
        </tr>
    </table>

    <input type="submit" value="Add to Roster" class="btn-sm btn-primary" /> @Html.ActionLink("Cancel", "EditRoom", new { id = ViewBag.RoomId })
}

@*<h3>Waitlist</h3>

<table class="table">
    <tr>
        <th><strong>Child Name/Identifier</strong></th>
        <th><strong>Date of Birth</strong></th>
        <th><strong>Prioritizations</strong></th>
        <th><strong></strong></th>
        <th><strong></strong></th>
    </tr>
    @for (var i = 0; i < Model.WaitlistChildren.Count; i++)
    {
        <tr>
            <td>
                @Html.HiddenFor(modelItem => Model.WaitlistChildren[i].ChildId)
                @Html.DisplayFor(modelItem => Model.WaitlistChildren[i].ChildName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.WaitlistChildren[i].DOB)
            </td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    }
</table>*@

<script>
        $(".CreateRostChildDatePicker").datepicker({
            changeMonth: true,
            changeYear: true,
            yearRange: "-12:+4"
        });
        $.validate({
            modules: 'date'
        });
        $('#crcdob').val('');
        $('#crcOverrideDate').val('');
        $("#tooltip").tooltip();
</script>

WTSite/Views/Rooms/CreateWaitlistChild.cshtml
@model WTSite.Models.RoomVM

@{
    ViewBag.Title = "Add New Child to Waitlist";
    Layout = "~/Views/Shared/_FacilityLayout.cshtml";
}
<link href="~/Content/multiple-select.css" rel="stylesheet" />
<script type="text/javascript" src="~/Scripts/MultipleSelect/multiple-select.js"></script>

@*<h2>Edit Room</h2>*@

@*<h3>Room Information</h3>

<table class="table">
    <tr>
        <td>
            @Html.HiddenFor(modelItem => Model.Room.childcare_facility_id)
            @Html.HiddenFor(modelItem => Model.Room.room_id)
            
        </td>
        <td>
            Room Age Range (Months): @Html.DisplayFor(modelItem => Model.Room.room_age_range_min) to @Html.DisplayFor(modelItem => Model.Room.room_age_range_max)
        </td>
        <td>
            Room Capacity: @Html.DisplayFor(modelItem => Model.Room.room_capacity)
        </td>
        <td>
            Waitlist Override Date (Optional): @Html.DisplayFor(modelItem => Model.WaitlistOverrideDate)
        </td>
    </tr>
</table>

<hr />*@

@*<h3>Roster</h3>


<table class="table">
    <tr>
        <th><strong>Child Name/Identifier</strong></th>
        <th><strong>Date of Birth</strong></th>
        <th><strong>Override Leave Date (Optional)</strong></th>
        <th><strong></strong></th>
    </tr>
    @for (var i = 0; i < Model.RosterChildren.Count; i++)
    {
        <tr>
            <td>
                @Html.HiddenFor(modelItem => Model.RosterChildren[i].ChildId)
                @Html.DisplayFor(modelItem => Model.RosterChildren[i].ChildName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.RosterChildren[i].DOB)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.RosterChildren[i].OverrideDate)
            </td>
            <td></td>
        </tr>
    }
</table>

<hr />*@

<br />
<h4>Add New Child to Waitlist</h4>
<h5><strong>Room:</strong> @Html.DisplayFor(modelItem => Model.Room.room_name)</h5>

@using (Html.BeginForm("AddWaitlistChild", "Rooms", FormMethod.Post, new { id = "submitNewWaitlistChildForm" }))
{
    <table class="table">
        <tr>
            <th><strong>Child Name/Identifier</strong> <font id="tooltip" style="font-size: 9px; font-weight:bold;"><a href="#" title="For security reasons, please use first names only or another unique identifier."><i class="fa fa-2x fa-question-circle"></i></a></font></th>
            <th><strong>Date of Birth</strong></th>
            <th><strong>Prioritizations</strong></th>
            <th><strong></strong></th>
            <th><strong></strong></th>
        </tr>
        @for (var i = 0; i < Model.WaitlistChildren.Count - 1; i++)
        {
            <tr>
                <td>
                    @Html.HiddenFor(modelItem => Model.WaitlistChildren[i].ChildId)
                    @Html.HiddenFor(modelItem => Model.WaitlistChildren[i].ChildName)
                    @Html.HiddenFor(modelItem => Model.WaitlistChildren[i].DOB)
                    @Html.DisplayFor(modelItem => Model.WaitlistChildren[i].ChildName)
                </td>
                <td>
                    @Convert.ToString(string.Format("{0:MM/dd/yyyy}", Model.WaitlistChildren[i].DOB))
                </td>
                <td style="display:none">
                    @Html.HiddenFor(m => m.ChildrenPrioritizationVMs[i].ChildId)
                    @Html.ListBoxFor(m => m.ChildrenPrioritizationVMs[i].PrioritizationID, (MultiSelectList)Model.ChildrenPrioritizationVMs[i].Prioritizations, new { @multiple = "multiple"})
                    <script>
                        $('select').multipleSelect();
                    </script>     
                </td>
                <td></td>
                <td></td>
            </tr>
        }
        <tr>
            <td>
                @Html.HiddenFor(modelItem => Model.Room.childcare_facility_id)
                @Html.HiddenFor(modelItem => Model.Room.room_name)
                @Html.HiddenFor(modelItem => Model.Room.room_age_range_min)
                @Html.HiddenFor(modelItem => Model.Room.room_age_range_max)
                @Html.HiddenFor(modelItem => Model.Room.room_capacity)
                @Html.HiddenFor(modelItem => Model.Room.room_id)
                @Html.HiddenFor(modelItem => Model.WaitlistChildren[Model.WaitlistChildren.Count - 1].ChildId)
                @Html.TextBoxFor(modelItem => Model.WaitlistChildren[Model.WaitlistChildren.Count - 1].ChildName, new { @data_validation="required alphanumeric", @class="form-control input", @maxlength="15", style="max-width:200px;", data_validation_error_msg = "Child identifier is required and cannot contain spaces." })
            </td>
            <td>
                @Html.TextBoxFor(modelItem => Model.WaitlistChildren[Model.WaitlistChildren.Count - 1].DOB, "{0:MM/dd/yyyy}", new { @style = "max-width:120px;", @class = "CreateWLChildDatePicker form-control input", @data_validation="required", @value="", @id= "cwcdob", data_validation_error_msg = "Date of birth is required." })
            </td>
            @if (Model.Prioritizations.Count > 0)
            {
                <td>
                    @Html.HiddenFor(modelItem => Model.ChildrenPrioritizationVMs[Model.WaitlistChildren.Count - 1].ChildId)
                    @Html.ListBoxFor(modelItem => Model.ChildrenPrioritizationVMs[Model.WaitlistChildren.Count - 1].PrioritizationID,
                    Model.ChildrenPrioritizationVMs[Model.WaitlistChildren.Count - 1].Prioritizations, new { multiple = "multiple" })
                    <script>
                        $('select').multipleSelect();
                    </script>
                </td>
            }
            else
            {
                <td></td>
            }
            <td></td>
        </tr>
    </table>

    <input type="submit" value="Add to Waitlist" class="btn-sm btn-primary" /> @Html.ActionLink("Cancel", "EditRoom", new { id = ViewBag.RoomId })
}
<script>
    
        $(".CreateWLChildDatePicker").datepicker({
            changeMonth: true,
            changeYear: true,
            yearRange: "-12:+4"
        });
        $.validate({
            modules: 'date'
        });
        $('#cwcdob').val('');
        
        $("#tooltip").tooltip();
</script>