WTSite/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WTSite.DAL;
using WTSite.Models;

namespace WTSite.Controllers
{
    public class SearchController : Controller
    {
        private SearchDAL sr = null;

        [HttpGet]
        public ActionResult SearchIndex()
        {
            // these are only used initially
            SearchResults searchCriteria = new SearchResults();
            searchCriteria.SearchCriteria = new SearchCriteria();
            searchCriteria.SearchCriteria.DOB = DateTime.Today;

            var statesArray = new[] { "AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "GU", "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME", "MH",
                "MI", "MN", "MO", "MS", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "PR", "PW", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VI", "VT",
                "WA", "WI", "WV", "WY"};

            var myStatesArray = new SelectListItem[56];

            for (var i = 0; i < statesArray.Length; i++)
            {
                myStatesArray[i] = new SelectListItem() { Text = statesArray[i].ToString(), Value = statesArray[i].ToString() };
            }

            ViewBag.myStatesArray = myStatesArray;

            return View(searchCriteria);
        }

        // GET: Partial View for criteria input
        public ActionResult SearchCriteriaPartial()
        {
            return PartialView();
        }

        // POST: Search by City, State Criteria
        [HttpPost]
        [ActionName("SearchCityState")]
        public ActionResult SearchCityState(SearchCriteria searchcriteria)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Error", "Home");
            }
            else
            {
                sr = new SearchDAL();

                // get all search results based on inputted criteria
                List<SearchResults> searchResults = sr.getSearchFacilitiesByCityState(new AlgorithmChild(searchcriteria.DOB), searchcriteria.City, searchcriteria.State);

                // stuff for list of states
                var statesArray = new[] { "AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "GU", "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME", "MH",
                "MI", "MN", "MO", "MS", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "PR", "PW", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VI", "VT",
                "WA", "WI", "WV", "WY"};

                var myStatesArray = new SelectListItem[56];

                for (var i = 0; i < statesArray.Length; i++)
                {
                    myStatesArray[i] = new SelectListItem() { Text = statesArray[i].ToString(), Value = statesArray[i].ToString() };
                }

                ViewBag.myStatesArray = myStatesArray;

                // stuff for partial view
                SearchResults inputtedCriteria = new SearchResults();
                inputtedCriteria.SearchCriteria = searchcriteria;
                TempData["inputtedCriteria"] = inputtedCriteria;

                // hack for the search result markers to be displayed next to facility names
                string[] resultMarkers = new string[searchResults.Count];
                for (var i = 0; i < searchResults.Count(); i++)
                {
                    resultMarkers[i] = "http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=" + (i + 1) + "|729EB3|FFFFFF";
                }

                ViewBag.ResultMarkers = resultMarkers;







                /////////////////////////////////test////////////////////////////////////
                //for (int i = 0; i < searchResults.Count; i++)
                //{
                //    // to hold each prioritization
                //    List<PrioritizationEED> prioritizationEEDS = new List<PrioritizationEED>();
                //    int priorityRank = 0;
                //    DateTime TempEED = new DateTime();

                //    SearchDAL EEDCalculator = new SearchDAL();
                //    rm = new RoomDAL(searchResults[i].Facility.childcare_facility_id);
                //    //rm = new RoomDAL(Facilities[i].childcare_facility_id);

                //    List<prioritization> facilityPrioritizations = rm.getFacilityPrioritizations();

                //    if (facilityPrioritizations.Count > 0)
                //    {
                //        foreach (prioritization prioritization in facilityPrioritizations)
                //        {
                //            priorityRank = prioritization.priority_rank;
                //            TempEED = EEDCalculator.getEED(searchResults[i].Facility, rooms[i].room_id, new AlgorithmChild(priorityRank));
                //            EEDsWithPrioritization.Add(new PrioritizationEED(prioritization, TempEED));
                //        }
                //    }
                //}
                /////////////////////////////////////test//////////////////////////////////



                return View(searchResults);
            }
        }

        // POST: Search by Zip Code Criteria
        [HttpPost]
        [ActionName("SearchZip")]
        public ActionResult SearchZip(SearchCriteria searchcriteria)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Error", "Home");
            }
            else
            {
                sr = new SearchDAL();

                // get all search results based on inputted criteria
                List<SearchResults> searchResults = sr.getSearchFacilitiesByZip(new AlgorithmChild(searchcriteria.DOB), searchcriteria.ZipCode);

                // stuff for list of states
                var statesArray = new[] { "AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "GU", "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME", "MH",
                "MI", "MN", "MO", "MS", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "PR", "PW", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VI", "VT",
                "WA", "WI", "WV", "WY"};

                var myStatesArray = new SelectListItem[56];

                for (var i = 0; i < statesArray.Length; i++)
                {
                    myStatesArray[i] = new SelectListItem() { Text = statesArray[i].ToString(), Value = statesArray[i].ToString() };
                }

                ViewBag.myStatesArray = myStatesArray;

                // stuff for partial view
                SearchResults inputtedCriteria = new SearchResults();
                inputtedCriteria.SearchCriteria = searchcriteria;
                TempData["inputtedCriteria"] = inputtedCriteria;

                // hack for the search result markers to be displayed next to facility names
                string[] resultMarkers = new string[searchResults.Count];
                for (var i = 0; i < searchResults.Count(); i++)
                {
                    resultMarkers[i] = "http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=" + (i + 1) + "|729EB3|FFFFFF";
                }

                ViewBag.ResultMarkers = resultMarkers;

                return View(searchResults);
            }
        }
    }
}

WTSite/Views/Search/SearchCityState.cshtml
@using WTSite.Models;
@model List<SearchResults>

@{
    ViewBag.Title = "Search Results";
    Layout = "~/Views/Shared/_LayoutStandard.cshtml";
}
    <link rel="stylesheet" type="text/css" href="~/Content/homepage/css/search.css" />

    <header id="top" class="searchheader" style="min-height:600px; max-height:750px;">
        <div class="header-content">
            <div class="header-content-inner">
                @Html.Partial("SearchCriteriaPartial", (SearchResults)TempData["inputtedCriteria"])
            </div>
        </div>
    </header>
    <section class="bg-primary" id="search">
        <div class="results-container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center" id="results">
                        Are you a licensed child care provider? Register your facility with us. <a href="@Url.Action("Register", "Account", routeValues: null)" class="btn btn-default btn-sm">GET STARTED</a>
                </div>
            </div>
        </div>
    </section>
    <section class="results-section">
        <div class="results-container">
            <div class="row">
                    <div class="col-md-6">
                        
                            @if (Model.Count == 0)
                            {
                                <p>Search returned no results.</p>
                            }
                            else
                            {
                                string mapsUrlString;
                                for (var i = 0; i < Model.Count; i++)
                                {
                                    mapsUrlString = "https://google.com/maps/dir//" + Model[i].Facility.address_line_1 + " " + Model[i].Facility.address_line_2 + " " + Model[i].Facility.city + ", " + Model[i].Facility.state + " " + Model[i].Facility.zip_code;
                                    <div class="row result-eed-row">
                                        <div class="col-md-5 result-eed">
                                            <h4><img src=@ViewBag.ResultMarkers[i] /> @Html.DisplayFor(modelItem => Model[i].Facility.childcare_facility_name)</h4>
                                            <p>
                                                @Html.DisplayFor(modelItem => Model[i].Facility.address_line_1) @Html.DisplayFor(modelItem => Model[i].Facility.address_line_2)<br />
                                                @Html.DisplayFor(modelItem => Model[i].Facility.city), @Html.DisplayFor(modelItem => Model[i].Facility.state) @Html.DisplayFor(modelItem => Model[i].Facility.zip_code)<br />
                                                @if (Model[i].Facility.phone_number != null)
                                                {
                                                    @*<strong>@Convert.ToInt64(Model[i].Facility.phone_number).ToString("(###)###-####")</strong>*@
                                                    <strong>@Model[i].Facility.phone_number</strong>
                                                }
                                            </p>
                                        </div>
                                        <div class="col-md-5 result-eed">
                                            <br /><h4>Estimated Enrollment Date<br /><strong>@Convert.ToString(string.Format("{0:MM/dd/yyyy}", Model[i].EED))</strong></h4>
                                            @if (Model[i].Facility.prioritizations.Count() > 0 && Model[i].EEDsWithPrioritization != null)
                                            {
                                                <div class="listToToggle">
                                                    <button type="button" class="btn-xs btn-primary togglePri">Show Prioritizations</button>
                                                    <div class="priList" hidden="hidden">
                                                        @for (var j = 0; j < Model[i].EEDsWithPrioritization.Count; j++)
                                                        {
                                                            <br />
                                                            @Html.DisplayFor(modelItem => Model[i].EEDsWithPrioritization[j].Prioritization.priority_rank)<font>.</font> @Html.DisplayFor(modelItem => Model[i].EEDsWithPrioritization[j].Prioritization.priority_name) <br />
                                                            <strong>Est. Date:</strong> @Convert.ToString(string.Format("{0:MM/dd/yyyy}", Model[i].EEDsWithPrioritization[j].EED))<br />
                                                        }
                                                    </div>
                                                </div>
                                            }
                                        </div>
                                        <div class="col-md-2 result-eed">
                                            <br />
                                            <a href="@mapsUrlString" target="_blank"><i class="fa fa-4x fa-map-marker"></i></a><font>&nbsp;&nbsp;</font>
                                            @if(Model[i].Facility.website != null)
                                            {
                                                <a href="http://@Model[i].Facility.website" target="_blank"><i class="fa fa-4x fa-globe"></i></a>
                                            }
                                        </div>
                                    </div>
                                }
                            }
                                    
                    </div>
                <div class="col-md-6 fillmap">
                    <div id="map"></div>
                </div>
            </div>
        </div>
    </section>
@*<div class="container-fluid">*@
                <!-- API Reference https://developers.google.com/maps/documentation/javascript/reference#MapOptions -->
                <script type="text/javascript">
                var geocoder;
                var map;
                var markerColor = '729EB3';
                var markerTextColor = 'FFFFFF';

                function initMap() {
                    geocoder = new google.maps.Geocoder();
                    var latlng = new google.maps.LatLng(61.190778, -149.818113); // UAA Coordinates
                    var mapOptions = {
                        zoom: 11,
                        center: latlng
                    }
                    map = new google.maps.Map(document.getElementById('map'), mapOptions);

                    var addresses = [];

                    @foreach (var item in Model)
        {
            @:addresses.push("@item.Facility.address_line_1" + "@item.Facility.address_line_2" + ", " + "@item.Facility.city" + ", " + "@item.Facility.state" + " " + "@item.Facility.zip_code");
                            }

                    console.log(addresses);

                    var a = 0;

                    var mapNumbers = [addresses.length];

                    for (var i = 0; i < addresses.length; i++) {
                        mapNumbers[i] = parseInt(i);
                        (function () {
                            var a = parseInt(i);
                            var address = addresses[i];
                            geocoder.geocode({ 'address': address }, function (results, status) {
                                if (status === google.maps.GeocoderStatus.OK) {
                                    map.setCenter(results[0].geometry.location);
                                    var marker = new google.maps.Marker({
                                        map: map,
                                        position: results[0].geometry.location,
                                        icon: 'http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=' + (mapNumbers[a] + 1) + '|' + markerColor + '|' + markerTextColor,
                                        title: (mapNumbers[a] + 1) // i dont think this works
                                    });
                                } else {
                                    //alert("Geocode was not successful for the following reason: " + status);
                                }
                            });
                        })();
                    }
                }
                </script>

                
            @*</div>*@

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDqdmyfpwCKM_02OnJRBDAHGiW0q1isyZM&callback=initMap" async defer></script>

    <script>
        $(function () {
            window.location = '#results';
        });
        $('.togglePri').click(function () {
            $(this).next().slideToggle();
            $(this).html(function (i, v) { return v === 'Hide Prioritizations' ? 'Show Prioritizations' : 'Hide Prioritizations' });
            //$(this).html('hide');
        });
        //$('.togglePri').click(function () {
        //    $(this).html('hide');
        //});

    $(function() {
        $("[name=toggler]").click(function(){
                $('.toHide').hide();
                $("#block-"+$(this).val()).show();
        });
    });

    $.validate({
        modules : 'date, security, toggleDisabled',
        disabledFormFilter: 'form.toggle-disabled',
        showErrorDialogs : false
    });


    $("#cityDOB").datepicker({
        changeMonth: true,
        changeYear: true,
        yearRange: "-12:+4"
    });

    $("#zipDOB").datepicker({
        changeMonth: true,
        changeYear: true,
        yearRange: "-12:+4"
    });


    $("#citystatedobtooltip").tooltip();
    $("#zipdobtooltip").tooltip();

    $('#mainNav').removeClass('affix-top').addClass('affix');

    $('#CityStateSearchButton').click(function () {
        if ($('#SearchCriteria_City, #cityDOB').hasClass('error')) {
            $('.CitysearchErrMsg').show();
        }
        else {
            $('.CitysearchErrMsg').hide();
        }
    });

    $('#ZipSearchButton').click(function () {
        if ($('#SearchCriteria_ZipCode, #zipDOB').hasClass('error')) {
            $('.ZipsearchErrMsg').show();
        }
        else {
            $('.ZipsearchErrMsg').hide();
        }
    });

    </script>  

WTSite/Views/Search/SearchCriteriaPartial.cshtml
@model WTSite.Models.SearchResults

    <div class="toHide" id="block-1">
        <div class="col-md-12">
            @using (Html.BeginForm("SearchCityState", "Search", FormMethod.Post, new { id = "submitCriteriaForSearch" }))
            {
                @Html.ValidationSummary(true)
                <div class="form-group" style="display:inline-block;">@Html.LabelFor(model => model.SearchCriteria.City)<br />
                    @Html.EditorFor(model => model.SearchCriteria.City, new { htmlAttributes = new { @class = "form-control-lg input-lg", @data_validation = "required" } })
                    @*@Html.ValidationMessageFor(model => model.SearchCriteria.City, "", new { @class = "text-danger" })*@
                </div>

                <div class="form-group" style="display:inline-block;">@Html.LabelFor(model => model.SearchCriteria.State)<br />
                    @Html.DropDownListFor(mode => Model.SearchCriteria.State, ViewBag.myStatesArray as IEnumerable<SelectListItem>, new { @class = "form-control-lg input-lg", @style = "width: 85px" })
                    @*@Html.ValidationMessageFor(model => model.SearchCriteria.State, "", new { @class = "text-danger" })*@
                </div>
            
                <div class="form-group">@Html.LabelFor(model => model.SearchCriteria.DOB) <font id="citystatedobtooltip" style="font-size: 9px; font-weight:bold;"><a href="#" title="Date of birth is used to give you an accurate estimated enrollment date for your child. None of this information is stored in our system."><i class="fa fa-2x fa-question-circle"></i></a></font><br />
                    @Html.TextBoxFor(model => Model.SearchCriteria.DOB, new { @class = "form-control-lg input-lg", @id = "cityDOB", @readonly="readonly", @data_validation = "required" })
                    @*@Html.ValidationMessageFor(model => model.SearchCriteria.DOB, "", new { @class = "text-danger" })*@
                </div>
                <span style="display:none;" class="CitysearchErrMsg"><strong>Please enter all required search criteria.</strong></span>
                <div class="form-group">
                    <div>
                        <input type="submit" id="CityStateSearchButton" value="Search" class="btn btn-xl btn-primary" />
                    </div>
                </div>
            }
        </div>
    </div>

    <div class="toHide" id="block-2" style="display:none;">
        <div class="col-md-12">
            @using (Html.BeginForm("SearchZip", "Search", FormMethod.Post, new { id = "submitCriteriaForSearch" }))
            {
                @Html.ValidationSummary(true)

                <div class="form-group" style="display:inline-block;">
                    @Html.LabelFor(model => model.SearchCriteria.ZipCode)<br />
                    @Html.EditorFor(model => model.SearchCriteria.ZipCode, new { htmlAttributes = new { @class = "form-control-lg input-lg", @data_validation = "number length", @data_validation_length = "min5", @maxlength = "5", @data_validation_error_msg = "Please enter a valid ZIP code." } })
                    @*@Html.ValidationMessageFor(model => model.SearchCriteria.ZipCode, "", new { @class = "text-danger" })*@
                </div>

            <div class="form-group">@Html.LabelFor(model => model.SearchCriteria.DOB) <font id="zipdobtooltip" style="font-size: 9px; font-weight:bold;"><a href="#" title="Date of birth is used to give you an accurate estimated enrollment date for your child. None of this information is stored in our system."><i class="fa fa-2x fa-question-circle"></i></a></font> <br />
                    @Html.TextBoxFor(model => Model.SearchCriteria.DOB, new { @class = "form-control-lg input-lg", @id="zipDOB", @readonly = "readonly", @value="", @data_validation = "required" })
                    @*@Html.ValidationMessageFor(model => model.SearchCriteria.DOB, "", new { @class = "text-danger" })*@
                </div>
                <span style="display:none;" class="ZipsearchErrMsg"><strong>Please enter all required search criteria.</strong></span>
                <div class="form-group">
                    <div>
                        <br />
                        <input type="submit" id="ZipSearchButton" value="Search" class="btn btn-xl btn-primary" />
                    </div>
                </div>
            }
        </div>
    </div>

<div class="row">
    Search by&nbsp;&nbsp;&nbsp;&nbsp;
    <label style="font-size: 18px; display:inline-block;"><input style="display:inline-block;" id="rdb1" type="radio" name="toggler" value="1" checked="checked" />City</label>&nbsp;&nbsp;&nbsp;&nbsp;
    <label style="font-size: 18px; display:inline-block;"><input style="display:inline-block;" id="rdb2" type="radio" name="toggler" value="2" />ZIP</label>
</div>
<div class="row">

</div>

WTSite/Views/Search/SearchIndex.cshtml
@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_LayoutStandard.cshtml";
}

    <link rel="stylesheet" type="text/css" href="~/Content/homepage/css/search.css" />
@using Microsoft.AspNet.Identity

<!--Search for facilities start-->  
    <header id="top">
        <div class="header-content">
            <div class="header-content-inner">
                <h1>Find a provider near you.</h1>
                <hr>
                @Html.Partial("SearchCriteriaPartial")
            </div>
        </div>
    </header>
    <section class="bg-primary" id="search">
        <div class="results-container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                        Are you a licensed child care provider? Register your facility with us. <a href="@Url.Action("Register", "Account", routeValues: null)" class="btn btn-default btn-sm">GET STARTED</a>
                </div>
            </div>
        </div>
    </section>
<!--Search for facilities end-->  

    <script>
        $("[name=toggler]").click(function(){
                $('.toHide').hide();
                $("#block-" + $(this).val()).show();
                $("#block-" + $(this).val()).find('input[type=text]').closest('input[type=text]').first().focus();
        });

        $.validate({
            modules : 'date, security, toggleDisabled',
            disabledFormFilter: 'form.toggle-disabled',
            showErrorDialogs : false
        });

        $("#cityDOB").datepicker({
            changeMonth: true,
            changeYear: true,
            yearRange: "-12:+4"
        });

        $("#zipDOB").datepicker({
            changeMonth: true,
            changeYear: true,
            yearRange: "-12:+4"
        });

        $("#zipDOB, #cityDOB").val('');

        $('#citystatedobtooltip').tooltip();
        $('#zipdobtooltip').tooltip();

        $('form').find('input[type=text],textarea,select').filter(':visible:first').focus();
                    
        $('#CityStateSearchButton').click(function () {
            if ($('#SearchCriteria_City, #cityDOB').hasClass('error')) {
                $('.CitysearchErrMsg').show();
            }
            else {
                $('.CitysearchErrMsg').hide();
            }
        });

        $('#ZipSearchButton').click(function () {
            if ($('#SearchCriteria_ZipCode, #zipDOB').hasClass('error')) {
                $('.ZipsearchErrMsg').show();
            }
            else {
                $('.ZipsearchErrMsg').hide();
            }
        });

        $("#rdb1").prop("checked", true)

    </script>