WTSite/Models/FacilityDetail.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace WTSite.Models
{
    public class FacilityDetail
    {
        public int FacilityID { get; set; }
        public int DetailID { get; set; }
        public string DetailName { get; set; }
        [Range(0,2)]
        public byte? DetailYesNo { get; set; }
        public string DetailComment { get; set; }

        public FacilityDetail() { }

        public FacilityDetail(int facilityid, int detailid, string detailname, byte? detailyesno, string detailcomment)
        {
            FacilityID = facilityid;
            DetailID = detailid;
            DetailName = detailname;

            if (detailyesno == null)
                DetailYesNo = 2;
            else
                DetailYesNo = detailyesno;

            DetailComment = detailcomment;
        }
    }
}

WTSite/Controllers/FacilityDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WTSite.DAL;
using WTSite.Models;

namespace WTSite.Controllers
{
    [Authorize(Roles = "Facility, Admin")]
    public class FacilityDetailsController : Controller
    {
        private WTEntities db = new WTEntities();
        private FacilityDetailsDAL fd = null;

        [HttpGet]
        public ActionResult FacilityDetailsIndex() 
        {
            int id = (int)Session["CurrentFacilityId"];
            //if (id == null)
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}
            //int abcd = id.Value;
            fd = new FacilityDetailsDAL(id);

            return View(fd.Details);
        }

        [HttpPost]
        [ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult FacilityDetailsEdit(List<FacilityDetail> facilityDetails)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Error", "Home");
            }
            // stops facilities from modifying other facility's data
            if (facilityDetails[0].FacilityID != (int)Session["CurrentFacilityId"])
            {
                return RedirectToAction("Error", "Home");
            }
            else
            {
                fd = new FacilityDetailsDAL(facilityDetails[0].FacilityID);

                for (int i = 0; i < facilityDetails.Count; i++)
                {
                    if (fd.Details[i].DetailYesNo == 2 && (facilityDetails[i].DetailYesNo == 1 || facilityDetails[i].DetailYesNo == 0))
                    {
                        fd.createFacilityDetail(facilityDetails[i].DetailID, facilityDetails[i].DetailYesNo, facilityDetails[i].DetailComment ?? "");
                    }
                    else if ((fd.Details[i].DetailYesNo == 1 || fd.Details[i].DetailYesNo == 0) && facilityDetails[i].DetailYesNo == 2)
                    {
                        fd.deleteFacilityDetail(facilityDetails[i].DetailID);
                    }
                    else if ((fd.Details[i].DetailYesNo == 1 || fd.Details[i].DetailYesNo == 0) && (facilityDetails[i].DetailYesNo == 1 || facilityDetails[i].DetailYesNo == 0))
                    {
                        fd.updateFacilityDetail(facilityDetails[i].DetailID, facilityDetails[i].DetailYesNo, facilityDetails[i].DetailComment ?? "");
                    }
                }
                return RedirectToAction("FacilityDetailsIndex");
            }       
        }

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

WTSite/Views/FacilityDetails/FacilityDetailsIndex.cshtml
@using WTSite.Models
@model List<FacilityDetail>

@{
    ViewBag.Title = "Facility Details";
    Layout = "~/Views/Shared/_FacilityLayout.cshtml";
}
<h4>Facility Details</h4>
@using (Html.BeginForm("Edit", "FacilityDetails", FormMethod.Post, new { id = "submitChangesForFacilitiesDetailsForm" }))
{
    @Html.ValidationSummary(true)
    @Html.AntiForgeryToken()
    <table class="table-condensed table-hover">
        <tr>
            <th class="col-md-3"><strong>Question</strong></th>
            <th class="col-md-1"><strong>Response</strong></th>
            <th class="col-md-8"><strong>Comments</strong></th>
        </tr>
        @for (var i = 0; i < Model.Count; i++)
        {
                <tr>
                    <td style="vertical-align: middle; width: 10%;">
                        @Html.HiddenFor(modelItem => Model[i].FacilityID)
                        @Html.HiddenFor(modelItem => Model[i].DetailID)
                        @Html.DisplayFor(modelItem => Model[i].DetailName)
                    </td>
                    <td style="width: 5%;">
                        @if (Model[i].DetailYesNo == 1)
                    {
                            @Html.DropDownListFor(modelItem => Model[i].DetailYesNo, new[] {
                            new SelectListItem() {Text = "Yes", Value = "1", Selected = true},
                            new SelectListItem() {Text = "No", Value = "0", Selected = false },
                            new SelectListItem() {Text = "N/A", Value = "2", Selected = false }
                        }, new { @class = "form-control input-sm detailYesNoDDL", @style = "width: 70px" })
                        }
                        else if (Model[i].DetailYesNo == 0)
                        {
                            @Html.DropDownListFor(modelItem => Model[i].DetailYesNo, new[] {
                            new SelectListItem() {Text = "Yes", Value = "1", Selected = false },
                            new SelectListItem() {Text = "No", Value = "0", Selected = true },
                            new SelectListItem() {Text = "N/A", Value = "2", Selected = false }
                        }, new { @class = "form-control input-sm detailYesNoDDL", @style = "width: 70px" })
                        }
                        else if (Model[i].DetailYesNo == 2)
                        {
                            @Html.DropDownListFor(modelItem => Model[i].DetailYesNo, new[] {
                            new SelectListItem() {Text = "Yes", Value = "1", Selected = false },
                            new SelectListItem() {Text = "No", Value = "0", Selected = false },
                            new SelectListItem() {Text = "N/A", Value = "2", Selected = true }
                        }, new { @class = "form-control input-sm detailYesNoDDL", @style = "width: 70px" })
                        }
                    </td>
                    <td style="width: 85%;">
                        @Html.TextBoxFor(modelItem => Model[i].DetailComment, "", new { @class = "form-control input-sm detailCommentTxtBox", @style = "width: 1000px;" })
                    </td>
                </tr>
        }
    </table>

    <input type="submit" value="Save Changes" class="btn-sm btn-primary" />
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        //logic: 
        //on load and on detailYesNoDDL value change,
        //if detailYesNoDDL.value is 2, disable next element class detailCommentTxtBox.
        //to disable the box: $('.detailCommentTxtBox').prop('disabled', true)
        //to find current value of DDL $('.detailYesNoDDL').val();

        $('.detailYesNoDDL').each(function () {
            var currentVal = $(this).val();
            if (currentVal == 2) {
                $(this).closest('td').next('td').find('.detailCommentTxtBox').prop('disabled', true);
            }
            else {
                $(this).closest('td').next('td').find('.detailCommentTxtBox').prop('disabled', false);
            }
        });

        //var currentDDL = $('.detailYesNoDDL');
        //var ddlIndex = $('.detailYesNoDDL').val();
        //if (currentDDL.val(ddlIndex) = 0)
        //    $('.detailCommentTxtBox').next.prop('disabled', true);
        $('.detailYesNoDDL').change(function () {
            var selectedValue = $(this).val();
                if (selectedValue == 2) {
                    var ok = window.confirm('By changing your response to N/A for this question, your comment will not be saved.');
                    if (ok == true)
                    {
                        $(this).closest('td').next('td').find('.detailCommentTxtBox').prop('disabled', true).val('');
                    }
                    else
                    {
                        $(this).val('--');
                    }
                }
                else
                {
                    $(this).closest('td').next('td').find('.detailCommentTxtBox').prop('disabled', false);
                }
            })
    });

</script>